<?php
$this->assets->addJs('media/js/angular.js');
$this->assets->addJs('media/js/angular-drag-and-drop-lists.js');
$this->assets->addJs('ngapp/Base/Class.js');
$this->assets->addJs('ngapp/Base/Manager.js');
$this->assets->addJs('ngapp/Lesson/LessonClass.js');
$this->assets->addJs('ngapp/LessonDays/LessonDayClass.js');
$this->assets->addJs('ngapp/LessonWeeks/LessonWeek.js');
$this->assets->addJs('ngapp/SchoolRoom/SchoolRoomClass.js');
$this->assets->addJs('ngapp/Subject/SubjectClass.js');
$this->assets->addJs('ngapp/Teacher/TeacherClass.js');
$this->assets->addJs('ngapp/SchoolClass/SchoolClassesClass.js');
$this->assets->addJs('ngapp/SchoolClass/SchoolClassesManager.js');
$this->assets->addJs('ngapp/Teacher/TeacherManager.js');
$this->assets->addJs('ngapp/Subject/SubjectManager.js');
$this->assets->addJs('ngapp/SchoolRoom/SchoolRoomManager.js');
$this->assets->addJs('ngapp/LessonDays/LessonDayManager.js');
$this->assets->addJs('ngapp/LessonWeeks/LessonWeekManager.js');
$this->assets->addJs('ngapp/Lesson/LessonManager.js');
//$this->assets->addJs('ngapp/Services/ManagerService.js');
$this->assets->addJs('ngapp/app.js');

// Так не делать!: on
//$ngapp_dirs_path = WWW_DIR . 'ngapp' . DIRECTORY_SEPARATOR;
//$ngapp_dirs = scandir($ngapp_dirs_path);
//foreach ($ngapp_dirs as $ngapp_dir)
//{
//	if ($ngapp_dir == '.' || $ngapp_dir == '..' || $ngapp_dir == '...')
//	{
//		continue;
//	}
//	elseif (is_file($ngapp_dirs_path.$ngapp_dir) && strpos($ngapp_dir, '.js') > 0)
//	{
//		$this->assets->addJs('ngapp/' . $ngapp_dir);
//	}
//	elseif (is_dir($ngapp_dirs_path.$ngapp_dir))
//	{
//		$ngapp_module_dirs = scandir($ngapp_dirs_path . $ngapp_dir);
//		foreach ($ngapp_module_dirs as $ngapp_module_file)
//		{
//			if ($ngapp_module_file == '.' || $ngapp_module_file == '..' || $ngapp_module_file == '...')
//			{
//				continue;
//			}
//			else
//			{
//				$this->assets->addJs('ngapp/' . $ngapp_dir . '/' . $ngapp_module_file);
//			}
//		}
//	}
//}
// Так не делать!: off
?>

<!--
  <div class="container mainWrapper">
	  <div class="row" ng-controller="SideBarsController">
		  <div class="upperTitleWrapper">
			  <div class="form-group">
				  <div class="weekDayTitle" ng-repeat="day in daysArr">
					  <div>{{day}}</div>
					  <div class="row">
						  <div class="weekDayNumber" ng-repeat="dayNumber in daysNumberArr">{{dayNumber}}</div>
					  </div>
				  </div>
			  </div>
		  </div>
		  <div class="classesSideBar">
			  <div ng-repeat="className in classesSidebarArr">{{className}}</div>
		  </div>
		  -->
<div class="row">
	<div class="lessonWrapper">
		<div class="form-group">
			<div class="simpleDemo" ng-controller="SimpleDemoController">
				<ul ng-repeat="list in models.lists"
				>
					<!-- dnd-dragover="dragoverCallback(event, index, external, type, list)" -->
					<li ng-repeat="item in list"
						dnd-list="item"
						dnd-disable-if="item.length > 0">
						<div ng-repeat="lesson in item"
							 dnd-draggable="lesson"
							 dnd-moved="item.splice($index, 1)"
							 dnd-effect-allowed="move"
						>
							{{lesson.lessonName}}
							<!-- {{list[$index].lessonName}} -->

						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
</div>


</div>
<!--
<div class="row">
	<div class="lessonWrapper">
		<div class="form-group">
			<div ng-controller="SimpleDemoController">
				<pre>{{modelAsJson}}</pre>
			</div>
		</div>
	</div>
</div>-->
