<!DOCTYPE html>
<html lang="en">
<head>
    <title>MyBootStrapReg</title>
    <meta charset="utf-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/style.less" rel="stylesheet/less">
    <script>
        less = {
            env: "development",
            async: false,
            fileAsync: false,
            poll: 1000,
            functions: {},
            dumpLineNumbers: "comments",
            relativeUrls: false,
            rootpath: ":/less/"
        };
    </script>
    <script src="js/less.js" type="text/javascript"></script>
</head>
<body>
<div class="container">
    
</div>
<script src="js/jquery-1.11.3.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/myScript.js"></script>
</body>
</html>
